name: application_parcours_d_exil
description: "Application en santé mentale pour les personnes bénéficiant d'un suivi à Parcours d'Exil, centre de santé dédié à la prise en charge du psychotraumatisme."

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.3.4
  video_player: ^2.9.0
  just_audio: ^0.9.42
  path_provider: ^2.0.14
  url_launcher: ^6.0.20
  shared_preferences: ^2.2.0
  flutter_svg: ^1.0.0
  floor: ^1.4.0
  sqflite: ^2.2.8+4
  file_picker: ^8.1.6
  audio_session: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  floor_generator: ^1.4.0
  build_runner: ^2.4.6
  sembast: ^3.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_parcours.png"

flutter:
  uses-material-design: true

#MODIFY WHEN ADDING NEW ASSETS
  assets:
    - assets/icons/parcoursSoins.png
    - assets/icons/santementale.png
    - assets/icons/aideAuQuotidien.png
    - assets/icons/psychoEducation.png
    - assets/icons/corporel.png
    - assets/icons/urgences.png
    - assets/icons/mesBesoins.png
    - assets/icons/favorite.png
    - assets/icons/settings.png
    - assets/icons/home.png
    - assets/icons/france.svg
    - assets/icons/uk.svg
    - assets/icons/audio_placeholder.png

    - assets/ressourcesPdE/Corporel/Assouplissement/Global/chaine_anterieure.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Global/chaine_laterale_1.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Global/chaine_laterale_2.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Global/chaine_posterieure.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/adducteurs.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/droit_anterieur.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/fessiers.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/illio_psoas.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/ischiojambier.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/quadriceps.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_inferieur/soleaire_triceps.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_superieur/epaules.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_superieur/grand_dorsal.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_superieur/trapeze_1.mp4
    - assets/ressourcesPdE/Corporel/Assouplissement/Membre_superieur/trapeze_2.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_inferieur/cheville.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_inferieur/genou.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_inferieur/hanche_1.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_inferieur/hanche_2.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_superieur/coude.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_superieur/epaule.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Membre_superieur/poignet.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Tronc/cervicale.mp4
    - assets/ressourcesPdE/Corporel/Mobilite/Tronc/rachis.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/cheville_1.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/cheville_2.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/cheville_3.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/cheville_4.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/epaules_re.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/epaules_ri.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/genou.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/hanche_abd.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/hanche_add.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/scapula_bas.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/scapula_haut.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/scapula_haut_2.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/AvecElastique/scapula_moyen.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/Gainage/sur_le_cote.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/Gainage/sur_le_dos.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/Gainage/sur_le_ventre_1.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/Gainage/sur_le_ventre_2.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/SurMarche/triceps_1.mp4
    - assets/ressourcesPdE/Corporel/Renforcement/SurMarche/triceps_2.mp4

    - assets/ressourcesPdE/Aide au quotidien/hospitals/saint_louis.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/hotel_dieu.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/avicenne.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/lariboisiere.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/pitie_salpetriere.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/saint_antoine.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/ambroise_pare.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/antoine_beclere.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/beaujon.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/kremlin_bicetre.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/bichat.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/corentin_celton.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/henri_mondor.pdf
    - assets/ressourcesPdE/Aide au quotidien/hospitals/europeen_georges_pompidou.pdf

    - assets/ressourcesPdE/Parcours de soin/Ateliers/Français/Atelier Français.pdf
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Français/Audio Atelier Français-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Français/Audio Atelier Français-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Informatique/Atelier Informatique.pdf
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Informatique/Audio Atelier informatique-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Informatique/Audio Atelier informatique-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Musique/Atelier musique.pdf
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Musique/Audio Atelier musique-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Ateliers/Musique/Audio Atelier musique-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Groupe de parole/Présentation groupe de parole.pdf
    - assets/ressourcesPdE/Parcours de soin/Groupe de parole/Groupe de parole-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Groupe de parole/Groupe de parole-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Médecins/Présentation médecin.pdf
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Médecins/Consultation médecin-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Médecins/Consultation médecin-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Ostéopathes/Présentation ostéopathe.pdf
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Ostéopathes/Consultation ostéopathe-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Ostéopathes/Consultation ostéopathe-FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Psychologues/Présentation psychologue.pdf
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Psychologues/Consultation psychologue-EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Professions de santé/Psychologues/Consultation_psychologue_FR.m4a
    - assets/ressourcesPdE/Parcours de soin/Suivi thérapeutique/Suivi thérapeutique.pdf
    - assets/ressourcesPdE/Parcours de soin/Suivi thérapeutique/Suivi_therapeutique_EN.m4a
    - assets/ressourcesPdE/Parcours de soin/Suivi thérapeutique/Suivi thérapeutique-FR.m4a

    - assets/ressourcesPdE/SanteMentale/AutoApaisement/apaiser_ses_pensees_avant_le_sommeil.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/concentration.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/lieu_ressource.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/premiere_experience.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/retrouver_de_l_energie.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/sensation_agreable.m4a
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_apaiserlespenseesavantlesommeil.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_concentration.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_energie.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_lieuressource.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_premiereexperience.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_sensationagreable.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/santementale_autoapaisement_souvenirsdifficiles.jpeg
    - assets/ressourcesPdE/SanteMentale/DeQuoiAsTuBesoin/respiration_abdominale.mp4
    - assets/ressourcesPdE/SanteMentale/EFT/eft.mp4
    - assets/ressourcesPdE/SanteMentale/EFT/havening.mp4
    - assets/ressourcesPdE/SanteMentale/EFT/ronde_EFT.pdf
    - assets/ressourcesPdE/SanteMentale/EFT/santementale_eft_equilibragepoursortirdelaconfusion.jpeg
    - assets/ressourcesPdE/SanteMentale/EFT/ttt.mp4
    - assets/ressourcesPdE/SanteMentale/HabitudeDeVieRythmeDeVie/Hygienedevie-EN.m4a
    - assets/ressourcesPdE/SanteMentale/HabitudeDeVieRythmeDeVie/Hygienedevie-FR.m4a
    - assets/ressourcesPdE/SanteMentale/HabitudeDeVieRythmeDeVie/Hygienedevie.pdf
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/ancrage_dans_l_instant_present.m4a
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/balayage_corporel.m4a
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/explorer_un_fruit_sens_par_sens.m4a
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/santementale_meditationpleineconscience_ancragedanslinstantpresent.jpeg
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/santementale_meditationpleineconscience_balayagecorporel.jpeg
    - assets/ressourcesPdE/SanteMentale/Meditationenpleineconscience/santementale_meditationpleineconscience_explorerunfruit.jpeg
    - assets/ressourcesPdE/SanteMentale/Respiration/exercice_46.mp4
    - assets/ressourcesPdE/SanteMentale/Respiration/exercice_55.mp4
    - assets/ressourcesPdE/SanteMentale/Respiration/presentation_coherence_cardiaque.mp4
    - assets/ressourcesPdE/SanteMentale/Stabilisation/ancrage_54321.m4a
    - assets/ressourcesPdE/SanteMentale/Stabilisation/ancrage_papillon.mp4
    - assets/ressourcesPdE/SanteMentale/Stabilisation/ancrage_papillon_pieds.m4a
    - assets/ressourcesPdE/SanteMentale/Stabilisation/contenant_1.mp3
    - assets/ressourcesPdE/SanteMentale/Stabilisation/ancrage_54321.jpeg
    - assets/ressourcesPdE/SanteMentale/Stabilisation/santementale_stabilisation_ancragepapillon.jpeg
    - assets/ressourcesPdE/SanteMentale/Stabilisation/santementale_stabilisation_ancragepapillonpieds.jpeg
    - assets/ressourcesPdE/SanteMentale/Stabilisation/santementale_stabilisation_contenantsimple.jpeg
    - assets/ressourcesPdE/SanteMentale/AutoApaisement/souvenirs.mp3

    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/psychotraumatisme.mp4
    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/Questcequelepsychotraumatisme.pdf
    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/bloque.mp4
    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/les_blessures_invisibles_troubles_stress_post_traumatique.mp4
    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/se_soigner_comprendre.mp4
    - assets/ressourcesPdE/PsychoEducation/Psychotraumatisme/la_sideration_ou_le_syndrome_de_lopossum.mp4
